name: PR Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5  # v5 is latest
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  # Automatically cache pip dependencies
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt  # Separate dev dependencies
    
    - name: Lint with ruff
      run: |
        ruff check .
    
    - name: Format check with ruff
      run: |
        ruff format --check .
    
    - name: Type check with mypy
      run: |
        mypy .
      continue-on-error: true  # Optional: don't fail build on type errors initially
